# Generated by Django 5.2.8 on 2025-12-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_catalogue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='telephone',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
